name: Deploy Personal Website

env:
  RESTURL_PORTFOLIO: ${{ secrets.RESTURL_PORTFOLIO }}
  GATSBY_RESTURL_PORTFOLIO: ${{ secrets.GATSBY_RESTURL_PORTFOLIO }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RESTURL_PORTFOLIO: ${{ secrets.RESTURL_PORTFOLIO }}
      GATSBY_RESTURL_PORTFOLIO: ${{ secrets.GATSBY_RESTURL_PORTFOLIO }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-seankerr-site-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-seankerr-site-build-
      - name: Install dependencies
        run: yarn install
      - name: Run Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Deployment info
        shell: bash
        run: |
          make deploy